<?php
require_once('../../back/classes/business/model/Client.php');
require_once('../../back/classes/business/model/Ingredient.php');
require_once('../../back/classes/database/DatabaseQuery.php');
require_once('../../back/classes/database/DatabaseConnection.php');
require_once('../../back/classes/database/persistence/ClientPersistence.php');
require_once('../../back/classes/database/persistence/RecipePersistence.php');
require_once('../../back/classes/business/facade/RecipeFacade.php');
include('../../back/functions/utils.php');
?>
