<?php
require_once('../../back/classes/business/model/Client.php');
require_once('../../back/classes/business/model/Recipe.php');
require_once('../../back/classes/business/model/Ingredient.php');
require_once('../../back/classes/business/process/recommenderSystem/RecommenderSystem.php');
require_once('../../back/classes/business/process/recommenderSystem/ContentBasedRecommenderSystem.php');
require_once('../../back/classes/business/process/informationRetrieval/Stemmer.php');
require_once('../../back/classes/business/process/informationRetrieval/Stem.php');
require_once('../../back/classes/business/process/informationRetrieval/ProcessText.php');
require_once('../../back/classes/business/process/informationRetrieval/ProcessTextSearch.php');
require_once('../../back/classes/business/process/informationRetrieval/StemmerFactory.php');
require_once('../../back/classes/business/process/informationRetrieval/FrenchStemmer.php');
require_once('../../back/classes/business/process/informationRetrieval/StopWords.php');
require_once('../../back/classes/database/DatabaseQuery.php');
require_once('../../back/classes/database/DatabaseConnection.php');
require_once('../../back/classes/database/persistence/RecipePersistence.php');
require_once('../../back/classes/database/persistence/ClientPersistence.php');
require_once('../../back/classes/business/service/DecisionTreeCluster.php');
require_once('../../back/classes/business/facade/RecipeFacade.php');
require_once('../../back/classes/business/facade/ClientFacade.php');
include('../../back/functions/utils.php');
include('../../back/utils/constants.php');
?>
